package com.suneee.project.model;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userid
     *
     * @mbggenerated Fri Oct 10 09:21:16 CST 2014
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Fri Oct 10 09:21:16 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Fri Oct 10 09:21:16 CST 2014
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userid
     *
     * @return the value of t_user.userid
     *
     * @mbggenerated Fri Oct 10 09:21:16 CST 2014
     */
    @NotNull(message = "{user.id.notNull}") 
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userid
     *
     * @param userid the value for t_user.userid
     *
     * @mbggenerated Fri Oct 10 09:21:16 CST 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Fri Oct 10 09:21:16 CST 2014
     */
    @NotEmpty(message = "{user.name.notNull}") 
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Fri Oct 10 09:21:16 CST 2014
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Fri Oct 10 09:21:16 CST 2014
     */
    @NotEmpty(message = "{user.password.notNull}") 
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Fri Oct 10 09:21:16 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }
}